/*
 * capture. It draws itself in, then it takes a picture: the frame on the screen snaps shut like a shutter, toward
 * its centre within the screen's plane, and opens again. Bring the pointer near and the shutter closes on it.
 * Generated by dogfood/hard/generate.py from the owner's story (dogfood/HARD.md); measured, not read off by eye.
 */
const { icon, spring, stepS, register, pointer, disposer, story, clamp, smooth, SPRING } = IF;

function mount({ stage, svg, read, src }, reach) {
  const bag = disposer();
  const ic = icon(svg, src);
  const [opening] = ic.hole(0);
  const front = ic.part("front", [0], { paint: "first" });
  ic.part("side", [2]);
  const win = ic.part("window", [opening, 1]);
  win.hi(true);
  const S = front.extent("u-up"), W = win.extent("u-up");
  const centre = W.pt((W.a[0] + W.a[1]) / 2, (W.b[0] + W.b[1]) / 2);
  const life = story(stage, {
    rest: { shut: 0, ink: 1 },
    poster: { shut: 0.85, ink: 1 },
    intro: { dur: 3000, from: { ink: 0 }, ease: "linear" },
    beats: [
      { dur: 1100 },
      { dur: 180, to: { shut: 1 }, ease: "in" },  // the shutter snaps shut
      { dur: 160 },
      { dur: 520, to: { shut: [-0.04, 0] }, ease: "out" }, // and opens again, a hair wide
      { dur: 1600 },
    ],
  });
  const hand = spring(0, SPRING.hand);
  let max = reach, label = "";
  const loop = register(stage, (dt) => {
    const x = life.step(dt), y = stepS(hand, dt);
    const v = life.values(life.held ? { shut: hand.x } : {});
    ic.ink(v.ink);
    /* the frame closes toward its centre within the screen's plane, to a sliver, never to nothing */
    const s = 1 - 0.92 * v.shut * max;
    win.stretch(s, s, "u-up", centre);
    const shown = v.ink < 1 ? "drawing" : v.shut < 0.02 && v.shut > -0.02 ? "rest" : v.shut > 0.8 ? "snap" : "shutter";
    if (shown !== label) { read.textContent = shown; label = shown; }
    return x || y;
  });
  const leave = () => { life.hold(false); loop.wake(); };
  bag.add(pointer(stage, {
    move(pt) {
      const near = 1 - smooth(30, 170, Math.hypot(pt[0] - centre[0], pt[1] - centre[1]));
      if (near <= 0) { leave(); return; }
      if (!life.held) { hand.x = life.values().shut; life.hold(true); }
      hand.t = near;
      loop.wake();
    },
    leave,
  }));
  bag.add(() => { loop.unregister(); while (svg.firstChild) svg.firstChild.remove(); });
  return { set(v) { max = clamp(v, 0, 1); loop.wake(); }, destroy: bag.dispose };
}

isoform({
  name: "capture",
  icon: "capture",
  variant: "rounded-left",
  means: "It takes a picture: the frame snaps shut like a shutter and opens again.",
  rules: [5, 8, 9],
  range: [0.6, 0.85, 1],
  mount,
});
