/*
 * maximize. It draws itself in, then it stretches: the bar stretches longer along its length as a solid,
 * holds, and returns. Bring the pointer near and it stretches toward you.
 * Generated by dogfood/hard/generate.py from the owner's story (dogfood/HARD.md); measured, not read off by eye.
 */
const { icon, spring, stepS, register, pointer, disposer, story, clamp, smooth, SPRING } = IF;

function mount({ stage, svg, read, src }, reach) {
  const bag = disposer();
  /* placed smaller than the default so the grown bar still fits. Face 0 is the bar's profile (its rounded ends are
     there) and face 1 the band swept back from it along -v, 65.1 deep at the default placement (measured: how far the
     band reaches past the profile along -v), scaled with it */
  const k = 0.62;
  const ic = icon(svg, src, { cx: 200, cy: 166, h: 220 * k, u: [0.866, 0.5], v: [-0.88, 0.47] });
  const bar = ic.part("bar", [0, 1], { solid: { front: 0, depth: [0, -65.1 * k, 0] } });
  bar.hi(true);
  const centre = [bar.rest.cx, bar.rest.cy];
  const life = story(stage, {
    rest: { grow: 0, ink: 1 },
    poster: { grow: 1, ink: 1 },
    intro: { dur: 3000, from: { ink: 0 }, ease: "linear" },
    beats: [
      { dur: 1000 },
      { dur: 650, to: { grow: [1.06, 1] }, ease: "out" }, // it stretches, a hair past, and settles
      { dur: 1400 },
      { dur: 550, to: { grow: 0 } },                      // and returns, softer
      { dur: 900 },
    ],
  });
  const hand = spring(0, SPRING.hand);
  let max = reach, label = "";
  const loop = register(stage, (dt) => {
    const x = life.step(dt), y = stepS(hand, dt);
    const v = life.values(life.held ? { grow: hand.x } : {});
    ic.ink(v.ink);
    /* along its length (u) only, within its profile's plane; the solid is re-drawn so its depth stays true (rule 09) */
    const s = 1 + (1.45 - 1) * v.grow * max;
    bar.grow(Math.abs(s - 1) < 1e-3 ? 1 : s, 1, centre);
    const shown = v.ink < 1 ? "drawing" : Math.abs(s - 1) < 0.01 ? "rest" : `long ${Math.round(s * 100)}%`;
    if (shown !== label) { read.textContent = shown; label = shown; }
    return x || y;
  });
  const leave = () => { life.hold(false); loop.wake(); };
  bag.add(pointer(stage, {
    move(pt) {
      const near = 1 - smooth(30, 170, Math.hypot(pt[0] - centre[0], pt[1] - centre[1]));
      if (near <= 0) { leave(); return; }
      if (!life.held) { hand.x = life.values().grow; life.hold(true); }
      hand.t = near;
      loop.wake();
    },
    leave,
  }));
  bag.add(() => { loop.unregister(); while (svg.firstChild) svg.firstChild.remove(); });
  return { set(v) { max = clamp(v, 0, 1); loop.wake(); }, destroy: bag.dispose };
}

isoform({
  name: "maximize",
  icon: "maximize",
  variant: "rounded-left",
  means: "The bar stretches: it stretches longer along its length, holds, and returns.",
  rules: [3, 8, 9],
  range: [0.6, 0.85, 1],
  mount,
});
