/*
 * subheader. It draws itself in, then the subheader opens: the window on the screen grows toward the screen's edges
 * within its own plane, holds, and settles back. Bring the pointer near and it opens toward you.
 * Generated by dogfood/hard/generate.py from the owner's story (dogfood/HARD.md); measured, not read off by eye.
 */
const { icon, spring, stepS, register, pointer, disposer, story, clamp, smooth, SPRING } = IF;

function mount({ stage, svg, read, src }, reach) {
  const bag = disposer();
  const ic = icon(svg, src);
  const [opening] = ic.hole(0);
  const front = ic.part("front", [0], { paint: "first" });
  ic.part("side", [2]);
  const win = ic.part("window", [opening, 1]);
  win.hi(true);
  const S = front.extent("u-up"), W = win.extent("u-up");
  /* the window grows toward the screen's edges, within the screen's plane: its target is the screen less a margin,
     reached by a stretch about the one point that maps each edge of the window onto the target's (per axis) */
  const inset = (e, k) => [e[0] + (e[1] - e[0]) * k, e[1] - (e[1] - e[0]) * k];
  const Ta = inset(S.a, 0.1), Tb = inset(S.b, 0.1);
  const aim = (w, t, f) => {
    const lo = w[0] + (t[0] - w[0]) * f, hi = w[1] + (t[1] - w[1]) * f, s = (hi - lo) / (w[1] - w[0]);
    return { s, at: Math.abs(s - 1) < 1e-3 ? (w[0] + w[1]) / 2 : (lo - s * w[0]) / (1 - s) };
  };
  const life = story(stage, {
    rest: { open: 0, ink: 1 },
    poster: { open: 1, ink: 1 },
    intro: { dur: 3000, from: { ink: 0 }, ease: "linear" },
    beats: [
      { dur: 1000 },
      { dur: 700, to: { open: [1.05, 1] }, ease: "out" }, // it opens, a hair past, and settles
      { dur: 1800 },
      { dur: 600, to: { open: 0 } },                      // and closes, softer than it opened
      { dur: 900 },
    ],
  });
  const hand = spring(0, SPRING.hand);
  let max = reach, label = "";
  const centre = W.pt((W.a[0] + W.a[1]) / 2, (W.b[0] + W.b[1]) / 2);
  const loop = register(stage, (dt) => {
    const x = life.step(dt), y = stepS(hand, dt);
    const v = life.values(life.held ? { open: hand.x } : {});
    ic.ink(v.ink);
    const f = v.open * max, A = aim(W.a, Ta, f), B = aim(W.b, Tb, f);
    win.stretch(A.s, B.s, "u-up", S.pt(A.at, B.at));
    const shown = v.ink < 1 ? "drawing" : v.open < 0.02 ? "rest" : `open ${Math.round(v.open * 100)}%`;
    if (shown !== label) { read.textContent = shown; label = shown; }
    return x || y;
  });
  const leave = () => { life.hold(false); loop.wake(); };
  bag.add(pointer(stage, {
    move(pt) {
      const near = 1 - smooth(30, 170, Math.hypot(pt[0] - centre[0], pt[1] - centre[1]));
      if (near <= 0) { leave(); return; }
      if (!life.held) { hand.x = life.values().open; life.hold(true); }
      hand.t = near;
      loop.wake();
    },
    leave,
  }));
  bag.add(() => { loop.unregister(); while (svg.firstChild) svg.firstChild.remove(); });
  return { set(v) { max = clamp(v, 0, 1); loop.wake(); }, destroy: bag.dispose };
}

isoform({
  name: "subheader",
  icon: "subheader",
  variant: "rounded-left",
  means: "The subheader opens: the window on the screen grows toward its edges, holds, and settles back.",
  rules: [3, 5, 9],
  range: [0.5, 0.8, 1],
  mount,
});
