#!/usr/bin/env python3
"""Writes the hard-icon figures (dogfood/HARD.md) from five family templates and measure.json (the kernel's own
measurement: face roles, and every morph target's opening as fractions of its own screen). Usage:
python3 generate.py measure.json   →   dogfood/hard/<id>/<id>.js"""
import json, os, sys

M = json.load(open(sys.argv[1]))
HERE = os.path.dirname(os.path.abspath(__file__))
HEAD = 'const { icon, spring, stepS, register, pointer, disposer, story, clamp, smooth, SPRING } = IF;\n'

def screen_parts(m):
    wall = f", {m['wall']}" if m['wall'] is not None else ""
    return f'''  const [opening] = ic.hole({m['front']});
  const front = ic.part("front", [{m['front']}], {{ paint: "first" }});
  ic.part("side", [{m['side']}]);
  const win = ic.part("window", [opening{wall}]);
  win.hi(true);
  const S = front.extent("u-up"), W = win.extent("u-up");'''

def hover(channel, target):
    return f'''  const leave = () => {{ life.hold(false); loop.wake(); }};
  bag.add(pointer(stage, {{
    move(pt) {{
      const near = 1 - smooth(30, 170, Math.hypot(pt[0] - {target}[0], pt[1] - {target}[1]));
      if (near <= 0) {{ leave(); return; }}
      if (!life.held) {{ hand.x = life.values().{channel}; life.hold(true); }}
      hand.t = near;
      loop.wake();
    }},
    leave,
  }}));'''

def wrap(doc, body, name, id_, means, rules, rng, cap):
    return f'''/*
{doc}
 * Generated by dogfood/hard/generate.py from the owner's story (dogfood/HARD.md); measured, not read off by eye.
 */
{HEAD}
function mount({{ stage, svg, read, src }}, reach) {{
  const bag = disposer();
{body}
  bag.add(() => {{ loop.unregister(); while (svg.firstChild) svg.firstChild.remove(); }});
  return {{ set(v) {{ max = clamp(v, 0, {cap}); loop.wake(); }}, destroy: bag.dispose }};
}}

isoform({{
  name: "{name}",
  icon: "{id_}",
  variant: "rounded-left",
  means: "{means}",
  rules: {rules},
  range: {rng},
  mount,
}});
'''

def grow(id_, word):
    m = M[id_]
    body = f'''  const ic = icon(svg, src);
{screen_parts(m)}
  /* the window grows toward the screen's edges, within the screen's plane: its target is the screen less a margin,
     reached by a stretch about the one point that maps each edge of the window onto the target's (per axis) */
  const inset = (e, k) => [e[0] + (e[1] - e[0]) * k, e[1] - (e[1] - e[0]) * k];
  const Ta = inset(S.a, 0.1), Tb = inset(S.b, 0.1);
  const aim = (w, t, f) => {{
    const lo = w[0] + (t[0] - w[0]) * f, hi = w[1] + (t[1] - w[1]) * f, s = (hi - lo) / (w[1] - w[0]);
    return {{ s, at: Math.abs(s - 1) < 1e-3 ? (w[0] + w[1]) / 2 : (lo - s * w[0]) / (1 - s) }};
  }};
  const life = story(stage, {{
    rest: {{ open: 0, ink: 1 }},
    poster: {{ open: 1, ink: 1 }},
    intro: {{ dur: 3000, from: {{ ink: 0 }}, ease: "linear" }},
    beats: [
      {{ dur: 1000 }},
      {{ dur: 700, to: {{ open: [1.05, 1] }}, ease: "out" }}, // it opens, a hair past, and settles
      {{ dur: 1800 }},
      {{ dur: 600, to: {{ open: 0 }} }},                      // and closes, softer than it opened
      {{ dur: 900 }},
    ],
  }});
  const hand = spring(0, SPRING.hand);
  let max = reach, label = "";
  const centre = W.pt((W.a[0] + W.a[1]) / 2, (W.b[0] + W.b[1]) / 2);
  const loop = register(stage, (dt) => {{
    const x = life.step(dt), y = stepS(hand, dt);
    const v = life.values(life.held ? {{ open: hand.x }} : {{}});
    ic.ink(v.ink);
    const f = v.open * max, A = aim(W.a, Ta, f), B = aim(W.b, Tb, f);
    win.stretch(A.s, B.s, "u-up", S.pt(A.at, B.at));
    const shown = v.ink < 1 ? "drawing" : v.open < 0.02 ? "rest" : `open ${{Math.round(v.open * 100)}}%`;
    if (shown !== label) {{ read.textContent = shown; label = shown; }}
    return x || y;
  }});
{hover("open", "centre")}'''
    doc = f' * {id_}. It draws itself in, then the {word} opens: the window on the screen grows toward the screen\'s edges\n * within its own plane, holds, and settles back. Bring the pointer near and it opens toward you.'
    return wrap(doc, body, id_, id_, f"The {word} opens: the window on the screen grows toward its edges, holds, and settles back.", [3, 5, 9], [0.5, 0.8, 1], 1)

def slide(id_):
    m = M[id_]
    body = f'''  const ic = icon(svg, src);
{screen_parts(m)}
  /* the three spots Isocons draws the window in (bottom-left, bottom-right, top-right), at this icon's own margins */
  const ma = Math.min(W.a[0] - S.a[0], S.a[1] - W.a[1]), mb = Math.min(W.b[0] - S.b[0], S.b[1] - W.b[1]);
  const wa = W.a[1] - W.a[0], wb = W.b[1] - W.b[0];
  const spots = [[S.a[0] + ma, S.b[0] + mb], [S.a[1] - ma - wa, S.b[0] + mb], [S.a[1] - ma - wa, S.b[1] - mb - wb]];
  const near0 = (s) => Math.hypot(s[0] - W.a[0], s[1] - W.b[0]);
  const home = spots.indexOf(spots.reduce((a, b) => (near0(a) <= near0(b) ? a : b)));
  const tour = [1, 2].map((k) => spots[(home + k) % 3]).map(([a, b]) => [a - W.a[0], b - W.b[0]]); // offsets from home
  const life = story(stage, {{
    rest: {{ go: 0, ink: 1 }},
    poster: {{ go: 1, ink: 1 }},
    intro: {{ dur: 3000, from: {{ ink: 0 }}, ease: "linear" }},
    beats: [
      {{ dur: 900 }},
      {{ dur: 800, to: {{ go: 1 }} }},  // to the next spot
      {{ dur: 700 }},
      {{ dur: 800, to: {{ go: 2 }} }},  // and the next
      {{ dur: 700 }},
      {{ dur: 800, to: {{ go: 3 }} }},  // and home
      {{ dur: 1, to: {{ go: 0 }} }},
      {{ dur: 800 }},
    ],
  }});
  const hand = spring(0, SPRING.hand);
  let max = reach, label = "";
  const centre = W.pt((W.a[0] + W.a[1]) / 2, (W.b[0] + W.b[1]) / 2);
  const loop = register(stage, (dt) => {{
    const x = life.step(dt), y = stepS(hand, dt);
    const v = life.values(life.held ? {{ go: hand.x }} : {{}});
    ic.ink(v.ink);
    /* through home → next → next → home, a straight glide between spots, scaled by how far it is let go */
    const g = ((v.go % 3) + 3) % 3, k = Math.floor(g), t = g - k;
    const at = (n) => (n % 3 === 0 ? [0, 0] : tour[(n % 3) - 1]);
    const p0 = at(k), p1 = at(k + 1), da = (p0[0] + (p1[0] - p0[0]) * t) * max, db = (p0[1] + (p1[1] - p0[1]) * t) * max;
    win.move(da, 0, db);
    const shown = v.ink < 1 ? "drawing" : Math.abs(da) + Math.abs(db) < 0.5 ? "rest" : ["home", "next", "corner"][Math.min(2, Math.round(g))];
    if (shown !== label) {{ read.textContent = shown; label = shown; }}
    return x || y;
  }});
{hover("go", "centre")}'''
    doc = f' * {id_}. It draws itself in, then its window glides, like a window snapped round a screen: to the next spot\n * Isocons draws it in, the next, and home. Bring the pointer near and it slides toward the next spot.'
    return wrap(doc, body, id_, id_, "The window glides round the screen to each spot Isocons draws it in, and comes home.", [3, 5, 9], [0.5, 0.8, 1], 1)

def morph(id_, target, verb):
    m, tg = M[id_], M[target]
    pts = json.dumps(tg['outline'])
    wall = m['wall'] if m['wall'] is not None else ""
    body = f'''  const ic = icon(svg, src);
{screen_parts(m)}
  /* {target}'s window, as fractions of its own screen (measured with the kernel), placed on this screen */
  const OTHER = {pts};
  const target = OTHER.map(([fa, fb]) => S.pt(S.a[0] + fa * (S.a[1] - S.a[0]), S.b[0] + fb * (S.b[1] - S.b[0])));
  const shape = ic.morph(opening, target, {{ hide: [{wall}] }}); // its inner wall belongs to its own outline
  const life = story(stage, {{
    rest: {{ become: 0, ink: 1 }},
    poster: {{ become: 1, ink: 1 }},
    intro: {{ dur: 3000, from: {{ ink: 0 }}, ease: "linear" }},
    beats: [
      {{ dur: 1000 }},
      {{ dur: 900, to: {{ become: 1 }} }},  // it becomes the other
      {{ dur: 1500 }},
      {{ dur: 900, to: {{ become: 0 }} }},  // and itself again
      {{ dur: 900 }},
    ],
  }});
  const hand = spring(0, SPRING.hand);
  let max = reach, label = "";
  const centre = W.pt((W.a[0] + W.a[1]) / 2, (W.b[0] + W.b[1]) / 2);
  const loop = register(stage, (dt) => {{
    const x = life.step(dt), y = stepS(hand, dt);
    const v = life.values(life.held ? {{ become: hand.x }} : {{}});
    ic.ink(v.ink);
    const t = v.become * max;
    shape.set(t);
    const shown = v.ink < 1 ? "drawing" : t < 0.02 ? "rest" : `{verb} ${{Math.round(t * 100)}}%`;
    if (shown !== label) {{ read.textContent = shown; label = shown; }}
    return x || y;
  }});
{hover("become", "centre")}'''
    doc = f' * {id_}. It draws itself in, then its window becomes {target}\'s: the outline flows into the other drawing\'s,\n * holds, and flows back. Bring the pointer near and it turns toward the other.'
    return wrap(doc, body, id_, id_, f"Its window flows into {target}'s outline, holds, and flows back.", [5, 8, 9], [0.6, 0.85, 1], 1)

def swell(id_):
    body = f'''  const ic = icon(svg, src);
  const dial = ic.part("dial", ic.paths.map((_, i) => i));
  dial.hi(true);
  const centre = [dial.rest.cx, dial.rest.cy];
  const life = story(stage, {{
    rest: {{ swell: 0, ink: 1 }},
    poster: {{ swell: 1, ink: 1 }},
    intro: {{ dur: 3000, from: {{ ink: 0 }}, ease: "linear" }},
    beats: [
      {{ dur: 1000 }},
      {{ dur: 450, to: {{ swell: [1, -0.15, 0] }}, ease: "out" }}, // pressed: it swells and settles, a hair under
      {{ dur: 700 }},
      {{ dur: 450, to: {{ swell: [1, -0.15, 0] }}, ease: "out" }}, // and again, as a choice is confirmed
      {{ dur: 1400 }},
    ],
  }});
  const hand = spring(0, SPRING.hand);
  let max = reach, label = "";
  const loop = register(stage, (dt) => {{
    const x = life.step(dt), y = stepS(hand, dt);
    const v = life.values(life.held ? {{ swell: hand.x }} : {{}});
    ic.ink(v.ink);
    const s = 1 + (max - 1) * v.swell;
    dial.stretch(s, s, "u-up", centre); // uniform within its plane: a true 3D swell (rule 09)
    const shown = v.ink < 1 ? "drawing" : v.swell < 0.02 && v.swell > -0.02 ? "rest" : "pressed";
    if (shown !== label) {{ read.textContent = shown; label = shown; }}
    return x || y;
  }});
{hover("swell", "centre")}'''
    doc = f' * {id_}. It draws itself in, then it is chosen: the ring swells in its own plane and settles, twice, like a\n * press confirmed. Bring the pointer near and it swells under it.'
    return wrap(doc, body, id_, id_, "An option is chosen: the ring swells in its own plane and settles, like a press confirmed.", [5, 8, 9], [1.05, 1.1, 1.16], 1.25)

def boomerang(id_, faces, front):
    src = open(os.path.join(HERE, '..', 'pilot-boomerang', 'boomerang.js')).read()
    a = src.index('function mount'); b = src.index('isoform({')
    body = src[a:b]
    body = body.replace('ic.part("boomerang", [0, 1, 2], { solid: { front: 0, depth:', f'ic.part("boomerang", {json.dumps(faces)}, {{ solid: {{ front: {front}, depth:')
    assert f'front: {front}' in body
    doc = f''' * {id_}, as a boomerang. It draws itself in, then it is thrown: it flies out on a loop, spinning as a solid in its
 * own plane, curves back and lands where it was drawn, its trail drawing on behind it. Bring the pointer near and it
 * is cocked back. Adapted from the approved stat-1 pilot (dogfood/pilot-boomerang); same depth, 44.7 along -v'''
    head = src[:src.index('function mount')]
    head = '/*\n' + doc + '\n * Generated by dogfood/hard/generate.py from the owner\'s story (dogfood/HARD.md).\n */\n' + head[head.index('const {'):]
    return head + body + f'''isoform({{
  name: "{id_}",
  icon: "{id_}",
  variant: "rounded-left",
  means: "Thrown like a boomerang: it flies out on a loop, spinning as a solid in its own plane, and comes back.",
  rules: [3, 8, 9, 11],
  range: [24, 34, 42],
  mount,
}});
'''

FIGS = {
  "radio-button-checked": lambda: swell("radio-button-checked"),
  "indeterminate-checkbox": lambda: morph("indeterminate-checkbox", "checkbox-blank", "square"),
  **{i: (lambda i=i, w=w: grow(i, w)) for i, w in [("dialog", "dialog"), ("tab", "tab"), ("chips", "chip"), ("subheader", "subheader"),
     ("dropdown", "dropdown"), ("float-desktop", "floating window"), ("float-landscape-2", "floating window"), ("fullscreen-portrait", "window")]},
  **{i: (lambda i=i: slide(i)) for i in ["position-bottom-left", "position-bottom-right", "position-top-right"]},
  "magnification-large": lambda: morph("magnification-large", "magnification-small", "small"),
  "magnification-small": lambda: morph("magnification-small", "magnification-large", "large"),
  "stat-0-double": lambda: boomerang("stat-0-double", [0, 1], 0),
  "stat-minus-1": lambda: boomerang("stat-minus-1", [0, 1, 2], 1),
}
for i, make in FIGS.items():
    d = os.path.join(HERE, i); os.makedirs(d, exist_ok=True)
    open(os.path.join(d, f"{i}.js"), "w").write(make())
print(len(FIGS), "figures")
